backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "project"
    label: project
    folder: "src/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}      
      - {
        label: "Tags", 
        name: "tags", 
        widget: "list", 
        field: {
          label: "Tag", 
          name: "tag_name", 
          widget: "string", 
          default: "post"
          }
        }
      - {label: "Featured Image", name: "imageFeatured", widget: "image"}
      - {
        label: "Other Images", 
        name: "images", 
        widget: "list", 
        field: {
          label: "Image", 
          name: "image_source", 
          widget: "image"
          }
      }
      - {label: "Image Alt", name: "imageFeaturedAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}