backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "project"
    label: project
    folder: "src/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "public/projects/media"
    public_folder: "/projects/media"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "markdown"

      - label: "Author"
        name: "author"
        widget: "string"
        default: "Matthew Davison"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        options:
          - { label: "Project", value: "project" }          
          - { label: "Featured", value: "featured" }
          - { label: "Private", value: "hidden" }
        default: ["project"]

      - label: "Featured Image"
        name: "imageFeatured"
        widget: "image"

      - label: "Featured Image Alt"
        name: "imageFeaturedAlt"
        widget: "string"

      - label: "Item Classes"
        name: "classes"
        widget: "select"
        multiple: true
        min: 2
        max: 2
        options:
          - { label: "Project", value: "project" }
          - { label: "Light", value: "project--light" }
          - { label: "Dark", value: "project--dark" }
        default: ["project"]

      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "resume"
    label: resume
    folder: "src/resumes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "public/resumes/media"
    public_folder: "/resumes/media"
    fields:
      - label: "Role"
        name: "role"
        widget: "string"

      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        options:
          - { label: "Resume", value: "resume" }          
          - { label: "Featured", value: "featured" }
          - { label: "Private", value: "hidden" }
        default: ["resume"]

      - label: "URL to Resume"
        name: "url"
        widget: "string"

      - label: "Featured Image"
        name: "imageFeatured"
        widget: "image"

      - label: "Featured Image Alt"
        name: "imageFeaturedAlt"
        widget: "string"

      - label: "Item Classes"
        name: "classes"
        widget: "select"
        multiple: true
        min: 2
        max: 2
        options:
          - { label: "Resume", value: "resume" }
          - { label: "Light", value: "resume--light" }
          - { label: "Dark", value: "resume--dark" }
        default: ["resume"]

          